// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGTjTkVR70lMwZSeDbrIzRgGPApn6UDzM',
    appId: '1:850207019875:web:ec4d973772b2fba21f7956',
    messagingSenderId: '850207019875',
    projectId: 'fire-base-4d8f4',
    authDomain: 'fire-base-4d8f4.firebaseapp.com',
    storageBucket: 'fire-base-4d8f4.firebasestorage.app',
    measurementId: 'G-PYMVHSPJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtqO0ZnxBEDHcve3Gp-UtBBpVTxyH8qs',
    appId: '1:850207019875:android:f0e12a2128702b1c1f7956',
    messagingSenderId: '850207019875',
    projectId: 'fire-base-4d8f4',
    storageBucket: 'fire-base-4d8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJn6WLlADQiIqahj30CAh80pEbSBYpx1w',
    appId: '1:850207019875:ios:09d493d8d0d281181f7956',
    messagingSenderId: '850207019875',
    projectId: 'fire-base-4d8f4',
    storageBucket: 'fire-base-4d8f4.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJn6WLlADQiIqahj30CAh80pEbSBYpx1w',
    appId: '1:850207019875:ios:09d493d8d0d281181f7956',
    messagingSenderId: '850207019875',
    projectId: 'fire-base-4d8f4',
    storageBucket: 'fire-base-4d8f4.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGTjTkVR70lMwZSeDbrIzRgGPApn6UDzM',
    appId: '1:850207019875:web:57c6198843fb43c81f7956',
    messagingSenderId: '850207019875',
    projectId: 'fire-base-4d8f4',
    authDomain: 'fire-base-4d8f4.firebaseapp.com',
    storageBucket: 'fire-base-4d8f4.firebasestorage.app',
    measurementId: 'G-184W1DS5ZC',
  );
}
